[package]
name = "splitncigar"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = "4.0"
rust-htslib = "0.49"   # or the latest version available
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"