[package]
name = "splitncigar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
rust-htslib = "0.49"   # or the latest version available

[[bin]]
name = "slowview"
path = "src/view.rs"

[[bin]]
name = "bamsummary"
path = "src/summary.rs"